name: Django CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - develop  # Déclenchement sur 'develop'
      - master   # Déclenchement sur 'master'
  pull_request:
    branches:
      - master   # Déclenchement sur les PR vers 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start containers
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for Django app to be ready
        run: |
          echo "Waiting for Django to be ready..."
          until curl -s http://localhost:8000 > /dev/null; do
            echo "Waiting for Django to start..."
            sleep 5
          done
          echo "Django is ready."

      - name: Run Django tests
        run: docker-compose exec -T app python manage.py test

      - name: Stop Docker containers
        run: docker-compose down
